
import java.applet.AudioClip;
import java.awt.Color;
import java.util.Collections;
import java.util.List;
import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JOptionPane;
import java.util.Random;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mp105
 */
public class codigo extends javax.swing.JFrame {
   
    /**
     * Creates new form codigo
     */
    private String user;
    private String dato;
    private Queue<String> listaTickets = new LinkedList<>();
    char letra = 'A';
    int num = 001;
    public codigo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public void setDato(String dato){
        this.dato = dato;
        jl_bienvenida.setText(dato);
        
    }
    
    public void nombre(String user){
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jl_bienvenida = new javax.swing.JLabel();
        lbdato = new javax.swing.JLabel();
        generarTicket = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        ale = new javax.swing.JTextField();
        linkelst = new javax.swing.JTextField();
        siguiente1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtf_turnoActual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jb_vaciarCola = new javax.swing.JButton();
        jtf_siguienteTurno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 149, 218));

        jl_bienvenida.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jl_bienvenida.setForeground(new java.awt.Color(255, 255, 255));
        jl_bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_bienvenida.setText("Bienvenido");

        lbdato.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lbdato.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jl_bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbdato, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_bienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(lbdato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        generarTicket.setBackground(new java.awt.Color(0, 149, 218));
        generarTicket.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        generarTicket.setForeground(new java.awt.Color(255, 255, 255));
        generarTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recibo.png"))); // NOI18N
        generarTicket.setText("Generar Ticket");
        generarTicket.setBorder(null);
        generarTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generarTicketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                generarTicketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                generarTicketMouseExited(evt);
            }
        });

        salir.setBackground(new java.awt.Color(0, 149, 218));
        salir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar-sesion.png"))); // NOI18N
        salir.setText("Salir");
        salir.setActionCommand("");
        salir.setBorder(null);
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });

        ale.setEditable(false);
        ale.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ale.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        linkelst.setEditable(false);
        linkelst.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        siguiente1.setBackground(new java.awt.Color(0, 149, 218));
        siguiente1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        siguiente1.setForeground(new java.awt.Color(255, 255, 255));
        siguiente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/siguiente-boton.png"))); // NOI18N
        siguiente1.setText("Siguiente Turno");
        siguiente1.setBorder(null);
        siguiente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siguiente1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                siguiente1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                siguiente1MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 149, 218));
        jLabel3.setText("Su Turno:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 149, 218));
        jLabel4.setText("Lista de espera: ");

        jtf_turnoActual.setEditable(false);
        jtf_turnoActual.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtf_turnoActual.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 149, 218));
        jLabel5.setText("Turno Actual: ");

        jb_vaciarCola.setBackground(new java.awt.Color(0, 149, 218));
        jb_vaciarCola.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jb_vaciarCola.setForeground(new java.awt.Color(255, 255, 255));
        jb_vaciarCola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caja-vacia (2).png"))); // NOI18N
        jb_vaciarCola.setText("Vaciar Cola");
        jb_vaciarCola.setActionCommand("");
        jb_vaciarCola.setBorder(null);
        jb_vaciarCola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_vaciarColaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jb_vaciarColaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jb_vaciarColaMouseExited(evt);
            }
        });

        jtf_siguienteTurno.setEditable(false);
        jtf_siguienteTurno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtf_siguienteTurno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 149, 218));
        jLabel6.setText("Siguiente Turno:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(linkelst, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ale)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_turnoActual)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_siguienteTurno)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb_vaciarCola, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(generarTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(siguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ale, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_turnoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_siguienteTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_vaciarCola, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(linkelst, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generarTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarTicketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarTicketMouseEntered
        generarTicket.setBackground(new Color(0,10,120));
        generarTicket.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_generarTicketMouseEntered

    private void generarTicketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarTicketMouseExited
        generarTicket.setBackground(new Color(0,149,218));
        generarTicket.setForeground(Color.WHITE);
    }//GEN-LAST:event_generarTicketMouseExited

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        salir.setBackground(new Color(0,10,120));
        salir.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        salir.setBackground(new Color(0,149,218));
        salir.setForeground(Color.WHITE);
    }//GEN-LAST:event_salirMouseExited
    
    private void generarTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarTicketMouseClicked
        StringBuilder sbTicket = new StringBuilder();
        String codigo = letra+String.valueOf(num);
        listaTickets.add(codigo);
        ale.setText(codigo);
        jtf_turnoActual.setText(listaTickets.peek());
        if(listaTickets.size()>1){
        LinkedList<String> sigTurno = (LinkedList<String>)listaTickets;
        jtf_siguienteTurno.setText(sigTurno.get(listaTickets.size()-(listaTickets.size()-1)));
        }
        for (String ticket : listaTickets) {
            sbTicket.append(ticket).append(" ---- ");
            
        }
        linkelst.setText(sbTicket.toString());
                if(ale.getText().equals(jtf_siguienteTurno.getText())){
            ale.setBackground(Color.GREEN);
            jtf_siguienteTurno.setBackground(Color.GREEN);
        }else{
                    ale.setBackground(new Color(245,245,245));
                    jtf_siguienteTurno.setBackground(new Color(245,245,245));
                }
        if(jtf_turnoActual.getText().equals(ale.getText())){
            AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/sonidoTurno.wav"));
            sonido.play();
            JOptionPane.showMessageDialog(null, "ES SU TURNO!","AVISO",JOptionPane.PLAIN_MESSAGE);
        }
        num++;
        if(num>9){
        num=1;
        letra++;
        }
    }//GEN-LAST:event_generarTicketMouseClicked

    private void siguiente1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguiente1MouseEntered
        siguiente1.setBackground(new Color(0,10,120));
        siguiente1.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_siguiente1MouseEntered

    private void siguiente1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguiente1MouseExited
        siguiente1.setBackground(new Color(0,149,218));
        siguiente1.setForeground(Color.WHITE);
    }//GEN-LAST:event_siguiente1MouseExited

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked

        JOptionPane.showMessageDialog(null, "Hasta luego "+ user);
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void jb_vaciarColaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_vaciarColaMouseClicked
        StringBuilder sb = new StringBuilder();
        listaTickets.clear();
        linkelst.setText("");
        ale.setText("");
        jtf_turnoActual.setText("");
        jtf_siguienteTurno.setText("");
        ale.setBackground(new Color(245,245,245));
        jtf_siguienteTurno.setBackground(new Color(245,245,245));
        JOptionPane.showMessageDialog(null, "Cola vaciada","VACIAR COLA",JOptionPane.PLAIN_MESSAGE);
        num=1;
        letra='A';
    }//GEN-LAST:event_jb_vaciarColaMouseClicked

    private void jb_vaciarColaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_vaciarColaMouseEntered
        jb_vaciarCola.setBackground(new Color(0,10,120));
        jb_vaciarCola.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jb_vaciarColaMouseEntered

    private void jb_vaciarColaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_vaciarColaMouseExited
        jb_vaciarCola.setBackground(new Color(0,149,218));
        jb_vaciarCola.setForeground(Color.WHITE);
    }//GEN-LAST:event_jb_vaciarColaMouseExited

    private void siguiente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguiente1MouseClicked
        listaTickets.poll();
        StringBuilder sbTicket = new StringBuilder();
        for (String ticket : listaTickets) {
            sbTicket.append(ticket).append(" ---- ");
            
        }
        linkelst.setText(sbTicket.toString());
        jtf_turnoActual.setText(listaTickets.peek());
        
        if(listaTickets.size()>1){
        LinkedList<String> sigTurno = (LinkedList<String>)listaTickets;
        jtf_siguienteTurno.setText(sigTurno.get(listaTickets.size()-(listaTickets.size()-1)));
        }
        if(jtf_turnoActual.getText().equals(ale.getText())){
            AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/sonidoTurno.wav"));
            sonido.play();
            JOptionPane.showMessageDialog(null, "ES SU TURNO!","AVISO",JOptionPane.PLAIN_MESSAGE);
        }
        if(ale.getText().equals(jtf_siguienteTurno.getText())){
            ale.setBackground(Color.GREEN);
            jtf_siguienteTurno.setBackground(Color.GREEN);
        }else{
                    ale.setBackground(new Color(245,245,245));
                    jtf_siguienteTurno.setBackground(new Color(245,245,245));
                }
        
    }//GEN-LAST:event_siguiente1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new codigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ale;
    private javax.swing.JButton generarTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jb_vaciarCola;
    private javax.swing.JLabel jl_bienvenida;
    private javax.swing.JTextField jtf_siguienteTurno;
    private javax.swing.JTextField jtf_turnoActual;
    private javax.swing.JLabel lbdato;
    private javax.swing.JTextField linkelst;
    private javax.swing.JButton salir;
    private javax.swing.JButton siguiente1;
    // End of variables declaration//GEN-END:variables
}
class numalet {
    private int id;
    private String value;

    public numalet(int id, String value) {
        this.id = id;
        this.value = value;
    }

    // Métodos getters y setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}