
import java.awt.Color;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mp105
 */
public class sistemadeespera extends javax.swing.JFrame {
         
        
    /**
     * Creates new form sistemadeespera
     */
    public sistemadeespera() {
        initComponents();
        this.setLocationRelativeTo(null);
        boton.setBackground(Color.WHITE);
        jl_validacion.setText("");
        jl_validacion2.setText("");
        jl_validacion.setIcon(null);
        jl_validacion2.setIcon(null);
        txtdato.setText("");
        
    }
 


    

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mensajebienvenido = new javax.swing.JLabel();
        cedula = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        usuario = new javax.swing.JLabel();
        numcedula = new javax.swing.JTextField();
        txtdato = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        boton = new javax.swing.JButton();
        jl_ndcMensaje = new javax.swing.JLabel();
        jl_userMensaje = new javax.swing.JLabel();
        jl_validacion = new javax.swing.JLabel();
        jl_validacion2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/7f597259893129.5a32dfbb9a433.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 149, 218));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Banco del Pacífico");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(0, 149, 218));

        mensajebienvenido.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        mensajebienvenido.setForeground(new java.awt.Color(255, 255, 255));
        mensajebienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajebienvenido.setText("Bienvenido");

        cedula.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cedula.setForeground(new java.awt.Color(255, 255, 255));
        cedula.setText("Ingrese su número de cédula");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        usuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Usuario");

        numcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numcedulaActionPerformed(evt);
            }
        });
        numcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numcedulaKeyReleased(evt);
            }
        });

        txtdato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatoActionPerformed(evt);
            }
        });
        txtdato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdatoKeyReleased(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        boton.setBackground(new java.awt.Color(51, 51, 51));
        boton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iniciar-sesion (1).png"))); // NOI18N
        boton.setText("Ingresar");
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMouseExited(evt);
            }
        });
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });

        jl_ndcMensaje.setForeground(new java.awt.Color(0, 149, 218));
        jl_ndcMensaje.setText("Número de cédula inválido!");

        jl_userMensaje.setForeground(new java.awt.Color(0, 149, 218));
        jl_userMensaje.setText("Usuario inválido!");

        jl_validacion.setText("jLabel3");

        jl_validacion2.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_ndcMensaje)
                                    .addComponent(jl_userMensaje))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtdato, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jl_validacion))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(numcedula, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cedula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jl_validacion2)))
                                .addGap(19, 19, 19))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(mensajebienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(mensajebienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdato, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_validacion))
                .addGap(3, 3, 3)
                .addComponent(jl_userMensaje)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_validacion2))
                .addGap(1, 1, 1)
                .addComponent(jl_ndcMensaje)
                .addGap(1, 1, 1)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseEntered
        boton.setBackground(new Color(0,10,120));
        boton.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_botonMouseEntered

    private void botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseExited
        boton.setBackground(Color.WHITE);
        boton.setForeground(Color.BLACK);
    }//GEN-LAST:event_botonMouseExited

    private void botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseClicked
        codigo ven1 = new codigo();
        ven1.setDato("Bienvenido "+txtdato.getText());
        
        if(numcedula.getText().equals("") || txtdato.getText().equals("")){
            jl_ndcMensaje.setForeground(Color.red);
            jl_userMensaje.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "FALTAN DATOS!","ERROR",JOptionPane.ERROR_MESSAGE);
        }else if(!numcedula.getText().matches("\\d+") || numcedula.getText().length()!=10 || txtdato.getText().matches(".*\\d.*")){
            numcedula.setText("");
            txtdato.setText("");
            jl_ndcMensaje.setForeground(Color.red);
            jl_userMensaje.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Usuario o número de cédula incorrectos","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            ven1.setVisible(true);
            this.dispose();
        }      
    }//GEN-LAST:event_botonMouseClicked

    private void txtdatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatoActionPerformed
        numcedula.requestFocus();
    }//GEN-LAST:event_txtdatoActionPerformed

    private void numcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numcedulaActionPerformed
        boton.doClick();
    }//GEN-LAST:event_numcedulaActionPerformed

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        
        codigo ven1 = new codigo();
        ven1.nombre(txtdato.getText());
        ven1.setDato("Bienvenido "+txtdato.getText());
        if(numcedula.getText().equals("") || txtdato.getText().equals("")){
            jl_ndcMensaje.setForeground(Color.red);
            jl_userMensaje.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "FALTAN DATOS!","ERROR",JOptionPane.ERROR_MESSAGE);
        }else if(!numcedula.getText().matches("\\d+") || numcedula.getText().length()!=10 || txtdato.getText().matches(".*\\d.*")){
            numcedula.setText("");
            txtdato.setText("");
            jl_ndcMensaje.setForeground(Color.red);
            jl_userMensaje.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Usuario o número de cédula incorrectos","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            ven1.setVisible(true);
            this.dispose();
        }   
    }//GEN-LAST:event_botonActionPerformed

    private void txtdatoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdatoKeyReleased
         jl_validacion.setIcon(null);
        String cadena = txtdato.getText();
        if (cadena.matches("^[a-zA-Z]{1,15}$")){//verifica que solo tenga letras, y que esté entre 1 y 15
            
            jl_validacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cheque-32px.png")));

        }else if(cadena.matches(".*[0-9].*")){//verifica que no hayan numeros ni otros simbolos en la cadena
           
            jl_validacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar-32px.png")));
        
        }else{
           
            jl_validacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar-32px.png")));
            
        }
    }//GEN-LAST:event_txtdatoKeyReleased

    private void numcedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numcedulaKeyReleased
        jl_validacion2.setIcon(null);
        String cadena2 = numcedula.getText();
        if(cadena2.matches("^[0-9]{10}$")){//verifica que tenga 10 dígitos
            
            jl_validacion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cheque-32px.png")));
        
        }else if (cadena2.matches(".*[a-zA-Z].*")){//verifica que no contenga letras ni simbolos
        
            jl_validacion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar-32px.png")));
        
        }
        else{
            
            jl_validacion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar-32px.png")));
            
        }     
    }//GEN-LAST:event_numcedulaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sistemadeespera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sistemadeespera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sistemadeespera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sistemadeespera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sistemadeespera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JLabel cedula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jl_ndcMensaje;
    private javax.swing.JLabel jl_userMensaje;
    private javax.swing.JLabel jl_validacion;
    private javax.swing.JLabel jl_validacion2;
    private javax.swing.JLabel mensajebienvenido;
    private javax.swing.JTextField numcedula;
    private javax.swing.JTextField txtdato;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
